/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ClientRouteRouteImport } from './routes/_client/route'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as ModeratorRouteRouteImport } from './routes/_moderator/route'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin/admin-analytics'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin-dashboard'
import { Route as AdminAdminModerationRouteImport } from './routes/_admin/admin-moderation'
import { Route as AdminAdminPagesRouteImport } from './routes/_admin/admin-pages'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin-settings'
import { Route as AdminAnnouncementsRouteImport } from './routes/_admin/announcements'
import { Route as AdminAppearanceRouteImport } from './routes/_admin/appearance'
import { Route as AdminHelpRouteImport } from './routes/_admin/help'
import { Route as AdminReportsSummaryRouteImport } from './routes/_admin/reports-summary'
import { Route as AdminUsersListRouteImport } from './routes/_admin/users-list'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as ClientBookmarksRouteImport } from './routes/_client/bookmarks'
import { Route as ClientEmbedRouteImport } from './routes/_client/embed'
import { Route as ClientJoinRouteImport } from './routes/_client/join'
import { Route as ClientNotificationsRouteImport } from './routes/_client/notifications'
import { Route as ClientSearchRouteImport } from './routes/_client/search'
import { Route as ClientSettingsRouteImport } from './routes/_client/settings'
import { Route as LandingCookiesRouteImport } from './routes/_landing/cookies'
import { Route as LandingPrivacyPolicyRouteImport } from './routes/_landing/privacy-policy'
import { Route as LandingTermsRouteImport } from './routes/_landing/terms'
import { Route as ModeratorHelpDocsRouteImport } from './routes/_moderator/help-docs'
import { Route as ModeratorModerationRouteImport } from './routes/_moderator/moderation'
import { Route as ModeratorModeratorDashboardRouteImport } from './routes/_moderator/moderator-dashboard'
import { Route as ModeratorModeratorReportsRouteImport } from './routes/_moderator/moderator-reports'
import { Route as ClientCategoryIndexRouteImport } from './routes/_client/category/index'
import { Route as ClientCategorySlugRouteImport } from './routes/_client/category/$slug'
import { Route as ClientEventsIndexRouteImport } from './routes/_client/events/index'
import { Route as ClientEventsIdRouteImport } from './routes/_client/events/$id'
import { Route as ClientEventsNewRouteImport } from './routes/_client/events/new'
import { Route as ClientGroupsIndexRouteImport } from './routes/_client/groups/index'
import { Route as ClientGroupsNewRouteImport } from './routes/_client/groups/new'
import { Route as ClientMessagesIndexRouteImport } from './routes/_client/messages/index'
import { Route as ClientMessagesIdRouteImport } from './routes/_client/messages/$id'
import { Route as ClientPagesSlugRouteImport } from './routes/_client/pages/$slug'
import { Route as ClientResourcesIndexRouteImport } from './routes/_client/resources/index'
import { Route as ClientTagsIndexRouteImport } from './routes/_client/tags/index'
import { Route as ClientTagsSlugRouteImport } from './routes/_client/tags/$slug'
import { Route as ClientThreadsIndexRouteImport } from './routes/_client/threads/index'
import { Route as ClientThreadsIdRouteImport } from './routes/_client/threads/$id'
import { Route as ClientThreadsNewRouteImport } from './routes/_client/threads/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ClientGroupsSlugIndexRouteImport } from './routes/_client/groups/$slug/index'
import { Route as ClientGroupsSlugEventsRouteImport } from './routes/_client/groups/$slug/events'
import { Route as ClientGroupsSlugMembersRouteImport } from './routes/_client/groups/$slug/members'
import { Route as ClientGroupsSlugSettingsRouteImport } from './routes/_client/groups/$slug/settings'
import { Route as ClientProfileUsernameIndexRouteImport } from './routes/_client/profile/$username/index'
import { Route as ClientProfileUsernameBadgesRouteImport } from './routes/_client/profile/$username/badges'
import { Route as ClientProfileUsernameEditRouteImport } from './routes/_client/profile/$username/edit'
import { Route as ClientProfileUsernameReputationRouteImport } from './routes/_client/profile/$username/reputation'
import { Route as ClientThreadsIdEditRouteImport } from './routes/_client/threads/$id.edit'
import { Route as ClientGroupsSlugForumIndexRouteImport } from './routes/_client/groups/$slug/forum/index'
import { Route as ClientGroupsSlugForumThreadIdRouteImport } from './routes/_client/groups/$slug/forum/$threadId'
import { Route as ClientThreadsThreadIdReplyReplyIdEditRouteImport } from './routes/_client/threads/$threadId.reply.$replyId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRouteRoute = ClientRouteRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorRouteRoute = ModeratorRouteRouteImport.update({
  id: '/_moderator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/admin-analytics',
  path: '/admin-analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminModerationRoute = AdminAdminModerationRouteImport.update({
  id: '/admin-moderation',
  path: '/admin-moderation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminPagesRoute = AdminAdminPagesRouteImport.update({
  id: '/admin-pages',
  path: '/admin-pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin-settings',
  path: '/admin-settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppearanceRoute = AdminAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsSummaryRoute = AdminReportsSummaryRouteImport.update({
  id: '/reports-summary',
  path: '/reports-summary',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersListRoute = AdminUsersListRouteImport.update({
  id: '/users-list',
  path: '/users-list',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ClientBookmarksRoute = ClientBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientEmbedRoute = ClientEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientJoinRoute = ClientJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientSearchRoute = ClientSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRouteRoute,
} as any)
const LandingCookiesRoute = LandingCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingPrivacyPolicyRoute = LandingPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingTermsRoute = LandingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LandingRouteRoute,
} as any)
const ModeratorHelpDocsRoute = ModeratorHelpDocsRouteImport.update({
  id: '/help-docs',
  path: '/help-docs',
  getParentRoute: () => ModeratorRouteRoute,
} as any)
const ModeratorModerationRoute = ModeratorModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => ModeratorRouteRoute,
} as any)
const ModeratorModeratorDashboardRoute =
  ModeratorModeratorDashboardRouteImport.update({
    id: '/moderator-dashboard',
    path: '/moderator-dashboard',
    getParentRoute: () => ModeratorRouteRoute,
  } as any)
const ModeratorModeratorReportsRoute =
  ModeratorModeratorReportsRouteImport.update({
    id: '/moderator-reports',
    path: '/moderator-reports',
    getParentRoute: () => ModeratorRouteRoute,
  } as any)
const ClientCategoryIndexRoute = ClientCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientCategorySlugRoute = ClientCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientEventsIndexRoute = ClientEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientEventsIdRoute = ClientEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientEventsNewRoute = ClientEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientGroupsIndexRoute = ClientGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientGroupsNewRoute = ClientGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientMessagesIndexRoute = ClientMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientMessagesIdRoute = ClientMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientPagesSlugRoute = ClientPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientResourcesIndexRoute = ClientResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientTagsIndexRoute = ClientTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientTagsSlugRoute = ClientTagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientThreadsIndexRoute = ClientThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientThreadsIdRoute = ClientThreadsIdRouteImport.update({
  id: '/threads/$id',
  path: '/threads/$id',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientThreadsNewRoute = ClientThreadsNewRouteImport.update({
  id: '/threads/new',
  path: '/threads/new',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientGroupsSlugIndexRoute = ClientGroupsSlugIndexRouteImport.update({
  id: '/groups/$slug/',
  path: '/groups/$slug/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientGroupsSlugEventsRoute = ClientGroupsSlugEventsRouteImport.update({
  id: '/groups/$slug/events',
  path: '/groups/$slug/events',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientGroupsSlugMembersRoute = ClientGroupsSlugMembersRouteImport.update({
  id: '/groups/$slug/members',
  path: '/groups/$slug/members',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientGroupsSlugSettingsRoute =
  ClientGroupsSlugSettingsRouteImport.update({
    id: '/groups/$slug/settings',
    path: '/groups/$slug/settings',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientProfileUsernameIndexRoute =
  ClientProfileUsernameIndexRouteImport.update({
    id: '/profile/$username/',
    path: '/profile/$username/',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientProfileUsernameBadgesRoute =
  ClientProfileUsernameBadgesRouteImport.update({
    id: '/profile/$username/badges',
    path: '/profile/$username/badges',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientProfileUsernameEditRoute =
  ClientProfileUsernameEditRouteImport.update({
    id: '/profile/$username/edit',
    path: '/profile/$username/edit',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientProfileUsernameReputationRoute =
  ClientProfileUsernameReputationRouteImport.update({
    id: '/profile/$username/reputation',
    path: '/profile/$username/reputation',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientThreadsIdEditRoute = ClientThreadsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ClientThreadsIdRoute,
} as any)
const ClientGroupsSlugForumIndexRoute =
  ClientGroupsSlugForumIndexRouteImport.update({
    id: '/groups/$slug/forum/',
    path: '/groups/$slug/forum/',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientGroupsSlugForumThreadIdRoute =
  ClientGroupsSlugForumThreadIdRouteImport.update({
    id: '/groups/$slug/forum/$threadId',
    path: '/groups/$slug/forum/$threadId',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientThreadsThreadIdReplyReplyIdEditRoute =
  ClientThreadsThreadIdReplyReplyIdEditRouteImport.update({
    id: '/threads/$threadId/reply/$replyId/edit',
    path: '/threads/$threadId/reply/$replyId/edit',
    getParentRoute: () => ClientRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-analytics': typeof AdminAdminAnalyticsRoute
  '/admin-dashboard': typeof AdminAdminDashboardRoute
  '/admin-moderation': typeof AdminAdminModerationRoute
  '/admin-pages': typeof AdminAdminPagesRoute
  '/admin-settings': typeof AdminAdminSettingsRoute
  '/announcements': typeof AdminAnnouncementsRoute
  '/appearance': typeof AdminAppearanceRoute
  '/help': typeof AdminHelpRoute
  '/reports-summary': typeof AdminReportsSummaryRoute
  '/users-list': typeof AdminUsersListRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/bookmarks': typeof ClientBookmarksRoute
  '/embed': typeof ClientEmbedRoute
  '/join': typeof ClientJoinRoute
  '/notifications': typeof ClientNotificationsRoute
  '/search': typeof ClientSearchRoute
  '/settings': typeof ClientSettingsRoute
  '/cookies': typeof LandingCookiesRoute
  '/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/terms': typeof LandingTermsRoute
  '/help-docs': typeof ModeratorHelpDocsRoute
  '/moderation': typeof ModeratorModerationRoute
  '/moderator-dashboard': typeof ModeratorModeratorDashboardRoute
  '/moderator-reports': typeof ModeratorModeratorReportsRoute
  '/category/$slug': typeof ClientCategorySlugRoute
  '/events/$id': typeof ClientEventsIdRoute
  '/events/new': typeof ClientEventsNewRoute
  '/groups/new': typeof ClientGroupsNewRoute
  '/messages/$id': typeof ClientMessagesIdRoute
  '/pages/$slug': typeof ClientPagesSlugRoute
  '/tags/$slug': typeof ClientTagsSlugRoute
  '/threads/$id': typeof ClientThreadsIdRouteWithChildren
  '/threads/new': typeof ClientThreadsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/category/': typeof ClientCategoryIndexRoute
  '/events/': typeof ClientEventsIndexRoute
  '/groups/': typeof ClientGroupsIndexRoute
  '/messages/': typeof ClientMessagesIndexRoute
  '/resources/': typeof ClientResourcesIndexRoute
  '/tags/': typeof ClientTagsIndexRoute
  '/threads/': typeof ClientThreadsIndexRoute
  '/groups/$slug/events': typeof ClientGroupsSlugEventsRoute
  '/groups/$slug/members': typeof ClientGroupsSlugMembersRoute
  '/groups/$slug/settings': typeof ClientGroupsSlugSettingsRoute
  '/profile/$username/badges': typeof ClientProfileUsernameBadgesRoute
  '/profile/$username/edit': typeof ClientProfileUsernameEditRoute
  '/profile/$username/reputation': typeof ClientProfileUsernameReputationRoute
  '/threads/$id/edit': typeof ClientThreadsIdEditRoute
  '/groups/$slug/': typeof ClientGroupsSlugIndexRoute
  '/profile/$username/': typeof ClientProfileUsernameIndexRoute
  '/groups/$slug/forum/$threadId': typeof ClientGroupsSlugForumThreadIdRoute
  '/groups/$slug/forum/': typeof ClientGroupsSlugForumIndexRoute
  '/threads/$threadId/reply/$replyId/edit': typeof ClientThreadsThreadIdReplyReplyIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-analytics': typeof AdminAdminAnalyticsRoute
  '/admin-dashboard': typeof AdminAdminDashboardRoute
  '/admin-moderation': typeof AdminAdminModerationRoute
  '/admin-pages': typeof AdminAdminPagesRoute
  '/admin-settings': typeof AdminAdminSettingsRoute
  '/announcements': typeof AdminAnnouncementsRoute
  '/appearance': typeof AdminAppearanceRoute
  '/help': typeof AdminHelpRoute
  '/reports-summary': typeof AdminReportsSummaryRoute
  '/users-list': typeof AdminUsersListRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/bookmarks': typeof ClientBookmarksRoute
  '/embed': typeof ClientEmbedRoute
  '/join': typeof ClientJoinRoute
  '/notifications': typeof ClientNotificationsRoute
  '/search': typeof ClientSearchRoute
  '/settings': typeof ClientSettingsRoute
  '/cookies': typeof LandingCookiesRoute
  '/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/terms': typeof LandingTermsRoute
  '/help-docs': typeof ModeratorHelpDocsRoute
  '/moderation': typeof ModeratorModerationRoute
  '/moderator-dashboard': typeof ModeratorModeratorDashboardRoute
  '/moderator-reports': typeof ModeratorModeratorReportsRoute
  '/category/$slug': typeof ClientCategorySlugRoute
  '/events/$id': typeof ClientEventsIdRoute
  '/events/new': typeof ClientEventsNewRoute
  '/groups/new': typeof ClientGroupsNewRoute
  '/messages/$id': typeof ClientMessagesIdRoute
  '/pages/$slug': typeof ClientPagesSlugRoute
  '/tags/$slug': typeof ClientTagsSlugRoute
  '/threads/$id': typeof ClientThreadsIdRouteWithChildren
  '/threads/new': typeof ClientThreadsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/category': typeof ClientCategoryIndexRoute
  '/events': typeof ClientEventsIndexRoute
  '/groups': typeof ClientGroupsIndexRoute
  '/messages': typeof ClientMessagesIndexRoute
  '/resources': typeof ClientResourcesIndexRoute
  '/tags': typeof ClientTagsIndexRoute
  '/threads': typeof ClientThreadsIndexRoute
  '/groups/$slug/events': typeof ClientGroupsSlugEventsRoute
  '/groups/$slug/members': typeof ClientGroupsSlugMembersRoute
  '/groups/$slug/settings': typeof ClientGroupsSlugSettingsRoute
  '/profile/$username/badges': typeof ClientProfileUsernameBadgesRoute
  '/profile/$username/edit': typeof ClientProfileUsernameEditRoute
  '/profile/$username/reputation': typeof ClientProfileUsernameReputationRoute
  '/threads/$id/edit': typeof ClientThreadsIdEditRoute
  '/groups/$slug': typeof ClientGroupsSlugIndexRoute
  '/profile/$username': typeof ClientProfileUsernameIndexRoute
  '/groups/$slug/forum/$threadId': typeof ClientGroupsSlugForumThreadIdRoute
  '/groups/$slug/forum': typeof ClientGroupsSlugForumIndexRoute
  '/threads/$threadId/reply/$replyId/edit': typeof ClientThreadsThreadIdReplyReplyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_client': typeof ClientRouteRouteWithChildren
  '/_landing': typeof LandingRouteRouteWithChildren
  '/_moderator': typeof ModeratorRouteRouteWithChildren
  '/_admin/admin-analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin-dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin-moderation': typeof AdminAdminModerationRoute
  '/_admin/admin-pages': typeof AdminAdminPagesRoute
  '/_admin/admin-settings': typeof AdminAdminSettingsRoute
  '/_admin/announcements': typeof AdminAnnouncementsRoute
  '/_admin/appearance': typeof AdminAppearanceRoute
  '/_admin/help': typeof AdminHelpRoute
  '/_admin/reports-summary': typeof AdminReportsSummaryRoute
  '/_admin/users-list': typeof AdminUsersListRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_client/bookmarks': typeof ClientBookmarksRoute
  '/_client/embed': typeof ClientEmbedRoute
  '/_client/join': typeof ClientJoinRoute
  '/_client/notifications': typeof ClientNotificationsRoute
  '/_client/search': typeof ClientSearchRoute
  '/_client/settings': typeof ClientSettingsRoute
  '/_landing/cookies': typeof LandingCookiesRoute
  '/_landing/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/_landing/terms': typeof LandingTermsRoute
  '/_moderator/help-docs': typeof ModeratorHelpDocsRoute
  '/_moderator/moderation': typeof ModeratorModerationRoute
  '/_moderator/moderator-dashboard': typeof ModeratorModeratorDashboardRoute
  '/_moderator/moderator-reports': typeof ModeratorModeratorReportsRoute
  '/_client/category/$slug': typeof ClientCategorySlugRoute
  '/_client/events/$id': typeof ClientEventsIdRoute
  '/_client/events/new': typeof ClientEventsNewRoute
  '/_client/groups/new': typeof ClientGroupsNewRoute
  '/_client/messages/$id': typeof ClientMessagesIdRoute
  '/_client/pages/$slug': typeof ClientPagesSlugRoute
  '/_client/tags/$slug': typeof ClientTagsSlugRoute
  '/_client/threads/$id': typeof ClientThreadsIdRouteWithChildren
  '/_client/threads/new': typeof ClientThreadsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_client/category/': typeof ClientCategoryIndexRoute
  '/_client/events/': typeof ClientEventsIndexRoute
  '/_client/groups/': typeof ClientGroupsIndexRoute
  '/_client/messages/': typeof ClientMessagesIndexRoute
  '/_client/resources/': typeof ClientResourcesIndexRoute
  '/_client/tags/': typeof ClientTagsIndexRoute
  '/_client/threads/': typeof ClientThreadsIndexRoute
  '/_client/groups/$slug/events': typeof ClientGroupsSlugEventsRoute
  '/_client/groups/$slug/members': typeof ClientGroupsSlugMembersRoute
  '/_client/groups/$slug/settings': typeof ClientGroupsSlugSettingsRoute
  '/_client/profile/$username/badges': typeof ClientProfileUsernameBadgesRoute
  '/_client/profile/$username/edit': typeof ClientProfileUsernameEditRoute
  '/_client/profile/$username/reputation': typeof ClientProfileUsernameReputationRoute
  '/_client/threads/$id/edit': typeof ClientThreadsIdEditRoute
  '/_client/groups/$slug/': typeof ClientGroupsSlugIndexRoute
  '/_client/profile/$username/': typeof ClientProfileUsernameIndexRoute
  '/_client/groups/$slug/forum/$threadId': typeof ClientGroupsSlugForumThreadIdRoute
  '/_client/groups/$slug/forum/': typeof ClientGroupsSlugForumIndexRoute
  '/_client/threads/$threadId/reply/$replyId/edit': typeof ClientThreadsThreadIdReplyReplyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-analytics'
    | '/admin-dashboard'
    | '/admin-moderation'
    | '/admin-pages'
    | '/admin-settings'
    | '/announcements'
    | '/appearance'
    | '/help'
    | '/reports-summary'
    | '/users-list'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/bookmarks'
    | '/embed'
    | '/join'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/cookies'
    | '/privacy-policy'
    | '/terms'
    | '/help-docs'
    | '/moderation'
    | '/moderator-dashboard'
    | '/moderator-reports'
    | '/category/$slug'
    | '/events/$id'
    | '/events/new'
    | '/groups/new'
    | '/messages/$id'
    | '/pages/$slug'
    | '/tags/$slug'
    | '/threads/$id'
    | '/threads/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/category/'
    | '/events/'
    | '/groups/'
    | '/messages/'
    | '/resources/'
    | '/tags/'
    | '/threads/'
    | '/groups/$slug/events'
    | '/groups/$slug/members'
    | '/groups/$slug/settings'
    | '/profile/$username/badges'
    | '/profile/$username/edit'
    | '/profile/$username/reputation'
    | '/threads/$id/edit'
    | '/groups/$slug/'
    | '/profile/$username/'
    | '/groups/$slug/forum/$threadId'
    | '/groups/$slug/forum/'
    | '/threads/$threadId/reply/$replyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-analytics'
    | '/admin-dashboard'
    | '/admin-moderation'
    | '/admin-pages'
    | '/admin-settings'
    | '/announcements'
    | '/appearance'
    | '/help'
    | '/reports-summary'
    | '/users-list'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/bookmarks'
    | '/embed'
    | '/join'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/cookies'
    | '/privacy-policy'
    | '/terms'
    | '/help-docs'
    | '/moderation'
    | '/moderator-dashboard'
    | '/moderator-reports'
    | '/category/$slug'
    | '/events/$id'
    | '/events/new'
    | '/groups/new'
    | '/messages/$id'
    | '/pages/$slug'
    | '/tags/$slug'
    | '/threads/$id'
    | '/threads/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/category'
    | '/events'
    | '/groups'
    | '/messages'
    | '/resources'
    | '/tags'
    | '/threads'
    | '/groups/$slug/events'
    | '/groups/$slug/members'
    | '/groups/$slug/settings'
    | '/profile/$username/badges'
    | '/profile/$username/edit'
    | '/profile/$username/reputation'
    | '/threads/$id/edit'
    | '/groups/$slug'
    | '/profile/$username'
    | '/groups/$slug/forum/$threadId'
    | '/groups/$slug/forum'
    | '/threads/$threadId/reply/$replyId/edit'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_client'
    | '/_landing'
    | '/_moderator'
    | '/_admin/admin-analytics'
    | '/_admin/admin-dashboard'
    | '/_admin/admin-moderation'
    | '/_admin/admin-pages'
    | '/_admin/admin-settings'
    | '/_admin/announcements'
    | '/_admin/appearance'
    | '/_admin/help'
    | '/_admin/reports-summary'
    | '/_admin/users-list'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/_client/bookmarks'
    | '/_client/embed'
    | '/_client/join'
    | '/_client/notifications'
    | '/_client/search'
    | '/_client/settings'
    | '/_landing/cookies'
    | '/_landing/privacy-policy'
    | '/_landing/terms'
    | '/_moderator/help-docs'
    | '/_moderator/moderation'
    | '/_moderator/moderator-dashboard'
    | '/_moderator/moderator-reports'
    | '/_client/category/$slug'
    | '/_client/events/$id'
    | '/_client/events/new'
    | '/_client/groups/new'
    | '/_client/messages/$id'
    | '/_client/pages/$slug'
    | '/_client/tags/$slug'
    | '/_client/threads/$id'
    | '/_client/threads/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_client/category/'
    | '/_client/events/'
    | '/_client/groups/'
    | '/_client/messages/'
    | '/_client/resources/'
    | '/_client/tags/'
    | '/_client/threads/'
    | '/_client/groups/$slug/events'
    | '/_client/groups/$slug/members'
    | '/_client/groups/$slug/settings'
    | '/_client/profile/$username/badges'
    | '/_client/profile/$username/edit'
    | '/_client/profile/$username/reputation'
    | '/_client/threads/$id/edit'
    | '/_client/groups/$slug/'
    | '/_client/profile/$username/'
    | '/_client/groups/$slug/forum/$threadId'
    | '/_client/groups/$slug/forum/'
    | '/_client/threads/$threadId/reply/$replyId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ClientRouteRoute: typeof ClientRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  ModeratorRouteRoute: typeof ModeratorRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_moderator': {
      id: '/_moderator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ModeratorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin-analytics': {
      id: '/_admin/admin-analytics'
      path: '/admin-analytics'
      fullPath: '/admin-analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin-dashboard': {
      id: '/_admin/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin-moderation': {
      id: '/_admin/admin-moderation'
      path: '/admin-moderation'
      fullPath: '/admin-moderation'
      preLoaderRoute: typeof AdminAdminModerationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin-pages': {
      id: '/_admin/admin-pages'
      path: '/admin-pages'
      fullPath: '/admin-pages'
      preLoaderRoute: typeof AdminAdminPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin-settings': {
      id: '/_admin/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/announcements': {
      id: '/_admin/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/appearance': {
      id: '/_admin/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof AdminAppearanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/help': {
      id: '/_admin/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/reports-summary': {
      id: '/_admin/reports-summary'
      path: '/reports-summary'
      fullPath: '/reports-summary'
      preLoaderRoute: typeof AdminReportsSummaryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/users-list': {
      id: '/_admin/users-list'
      path: '/users-list'
      fullPath: '/users-list'
      preLoaderRoute: typeof AdminUsersListRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_client/bookmarks': {
      id: '/_client/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof ClientBookmarksRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/embed': {
      id: '/_client/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof ClientEmbedRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/join': {
      id: '/_client/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof ClientJoinRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/notifications': {
      id: '/_client/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/search': {
      id: '/_client/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ClientSearchRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/settings': {
      id: '/_client/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_landing/cookies': {
      id: '/_landing/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof LandingCookiesRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/privacy-policy': {
      id: '/_landing/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LandingPrivacyPolicyRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/terms': {
      id: '/_landing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LandingTermsRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_moderator/help-docs': {
      id: '/_moderator/help-docs'
      path: '/help-docs'
      fullPath: '/help-docs'
      preLoaderRoute: typeof ModeratorHelpDocsRouteImport
      parentRoute: typeof ModeratorRouteRoute
    }
    '/_moderator/moderation': {
      id: '/_moderator/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModeratorModerationRouteImport
      parentRoute: typeof ModeratorRouteRoute
    }
    '/_moderator/moderator-dashboard': {
      id: '/_moderator/moderator-dashboard'
      path: '/moderator-dashboard'
      fullPath: '/moderator-dashboard'
      preLoaderRoute: typeof ModeratorModeratorDashboardRouteImport
      parentRoute: typeof ModeratorRouteRoute
    }
    '/_moderator/moderator-reports': {
      id: '/_moderator/moderator-reports'
      path: '/moderator-reports'
      fullPath: '/moderator-reports'
      preLoaderRoute: typeof ModeratorModeratorReportsRouteImport
      parentRoute: typeof ModeratorRouteRoute
    }
    '/_client/category/': {
      id: '/_client/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof ClientCategoryIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/category/$slug': {
      id: '/_client/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof ClientCategorySlugRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/events/': {
      id: '/_client/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof ClientEventsIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/events/$id': {
      id: '/_client/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof ClientEventsIdRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/events/new': {
      id: '/_client/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof ClientEventsNewRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/groups/': {
      id: '/_client/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof ClientGroupsIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/groups/new': {
      id: '/_client/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof ClientGroupsNewRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/messages/': {
      id: '/_client/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof ClientMessagesIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/messages/$id': {
      id: '/_client/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof ClientMessagesIdRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/pages/$slug': {
      id: '/_client/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof ClientPagesSlugRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/resources/': {
      id: '/_client/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ClientResourcesIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/tags/': {
      id: '/_client/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof ClientTagsIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/tags/$slug': {
      id: '/_client/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof ClientTagsSlugRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/threads/': {
      id: '/_client/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof ClientThreadsIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/threads/$id': {
      id: '/_client/threads/$id'
      path: '/threads/$id'
      fullPath: '/threads/$id'
      preLoaderRoute: typeof ClientThreadsIdRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/threads/new': {
      id: '/_client/threads/new'
      path: '/threads/new'
      fullPath: '/threads/new'
      preLoaderRoute: typeof ClientThreadsNewRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/groups/$slug/': {
      id: '/_client/groups/$slug/'
      path: '/groups/$slug'
      fullPath: '/groups/$slug/'
      preLoaderRoute: typeof ClientGroupsSlugIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/groups/$slug/events': {
      id: '/_client/groups/$slug/events'
      path: '/groups/$slug/events'
      fullPath: '/groups/$slug/events'
      preLoaderRoute: typeof ClientGroupsSlugEventsRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/groups/$slug/members': {
      id: '/_client/groups/$slug/members'
      path: '/groups/$slug/members'
      fullPath: '/groups/$slug/members'
      preLoaderRoute: typeof ClientGroupsSlugMembersRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/groups/$slug/settings': {
      id: '/_client/groups/$slug/settings'
      path: '/groups/$slug/settings'
      fullPath: '/groups/$slug/settings'
      preLoaderRoute: typeof ClientGroupsSlugSettingsRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/profile/$username/': {
      id: '/_client/profile/$username/'
      path: '/profile/$username'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof ClientProfileUsernameIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/profile/$username/badges': {
      id: '/_client/profile/$username/badges'
      path: '/profile/$username/badges'
      fullPath: '/profile/$username/badges'
      preLoaderRoute: typeof ClientProfileUsernameBadgesRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/profile/$username/edit': {
      id: '/_client/profile/$username/edit'
      path: '/profile/$username/edit'
      fullPath: '/profile/$username/edit'
      preLoaderRoute: typeof ClientProfileUsernameEditRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/profile/$username/reputation': {
      id: '/_client/profile/$username/reputation'
      path: '/profile/$username/reputation'
      fullPath: '/profile/$username/reputation'
      preLoaderRoute: typeof ClientProfileUsernameReputationRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/threads/$id/edit': {
      id: '/_client/threads/$id/edit'
      path: '/edit'
      fullPath: '/threads/$id/edit'
      preLoaderRoute: typeof ClientThreadsIdEditRouteImport
      parentRoute: typeof ClientThreadsIdRoute
    }
    '/_client/groups/$slug/forum/': {
      id: '/_client/groups/$slug/forum/'
      path: '/groups/$slug/forum'
      fullPath: '/groups/$slug/forum/'
      preLoaderRoute: typeof ClientGroupsSlugForumIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/groups/$slug/forum/$threadId': {
      id: '/_client/groups/$slug/forum/$threadId'
      path: '/groups/$slug/forum/$threadId'
      fullPath: '/groups/$slug/forum/$threadId'
      preLoaderRoute: typeof ClientGroupsSlugForumThreadIdRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/threads/$threadId/reply/$replyId/edit': {
      id: '/_client/threads/$threadId/reply/$replyId/edit'
      path: '/threads/$threadId/reply/$replyId/edit'
      fullPath: '/threads/$threadId/reply/$replyId/edit'
      preLoaderRoute: typeof ClientThreadsThreadIdReplyReplyIdEditRouteImport
      parentRoute: typeof ClientRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminModerationRoute: typeof AdminAdminModerationRoute
  AdminAdminPagesRoute: typeof AdminAdminPagesRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAppearanceRoute: typeof AdminAppearanceRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminReportsSummaryRoute: typeof AdminReportsSummaryRoute
  AdminUsersListRoute: typeof AdminUsersListRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminModerationRoute: AdminAdminModerationRoute,
  AdminAdminPagesRoute: AdminAdminPagesRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAppearanceRoute: AdminAppearanceRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminReportsSummaryRoute: AdminReportsSummaryRoute,
  AdminUsersListRoute: AdminUsersListRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ClientThreadsIdRouteChildren {
  ClientThreadsIdEditRoute: typeof ClientThreadsIdEditRoute
}

const ClientThreadsIdRouteChildren: ClientThreadsIdRouteChildren = {
  ClientThreadsIdEditRoute: ClientThreadsIdEditRoute,
}

const ClientThreadsIdRouteWithChildren = ClientThreadsIdRoute._addFileChildren(
  ClientThreadsIdRouteChildren,
)

interface ClientRouteRouteChildren {
  ClientBookmarksRoute: typeof ClientBookmarksRoute
  ClientEmbedRoute: typeof ClientEmbedRoute
  ClientJoinRoute: typeof ClientJoinRoute
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientSearchRoute: typeof ClientSearchRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientCategorySlugRoute: typeof ClientCategorySlugRoute
  ClientEventsIdRoute: typeof ClientEventsIdRoute
  ClientEventsNewRoute: typeof ClientEventsNewRoute
  ClientGroupsNewRoute: typeof ClientGroupsNewRoute
  ClientMessagesIdRoute: typeof ClientMessagesIdRoute
  ClientPagesSlugRoute: typeof ClientPagesSlugRoute
  ClientTagsSlugRoute: typeof ClientTagsSlugRoute
  ClientThreadsIdRoute: typeof ClientThreadsIdRouteWithChildren
  ClientThreadsNewRoute: typeof ClientThreadsNewRoute
  ClientCategoryIndexRoute: typeof ClientCategoryIndexRoute
  ClientEventsIndexRoute: typeof ClientEventsIndexRoute
  ClientGroupsIndexRoute: typeof ClientGroupsIndexRoute
  ClientMessagesIndexRoute: typeof ClientMessagesIndexRoute
  ClientResourcesIndexRoute: typeof ClientResourcesIndexRoute
  ClientTagsIndexRoute: typeof ClientTagsIndexRoute
  ClientThreadsIndexRoute: typeof ClientThreadsIndexRoute
  ClientGroupsSlugEventsRoute: typeof ClientGroupsSlugEventsRoute
  ClientGroupsSlugMembersRoute: typeof ClientGroupsSlugMembersRoute
  ClientGroupsSlugSettingsRoute: typeof ClientGroupsSlugSettingsRoute
  ClientProfileUsernameBadgesRoute: typeof ClientProfileUsernameBadgesRoute
  ClientProfileUsernameEditRoute: typeof ClientProfileUsernameEditRoute
  ClientProfileUsernameReputationRoute: typeof ClientProfileUsernameReputationRoute
  ClientGroupsSlugIndexRoute: typeof ClientGroupsSlugIndexRoute
  ClientProfileUsernameIndexRoute: typeof ClientProfileUsernameIndexRoute
  ClientGroupsSlugForumThreadIdRoute: typeof ClientGroupsSlugForumThreadIdRoute
  ClientGroupsSlugForumIndexRoute: typeof ClientGroupsSlugForumIndexRoute
  ClientThreadsThreadIdReplyReplyIdEditRoute: typeof ClientThreadsThreadIdReplyReplyIdEditRoute
}

const ClientRouteRouteChildren: ClientRouteRouteChildren = {
  ClientBookmarksRoute: ClientBookmarksRoute,
  ClientEmbedRoute: ClientEmbedRoute,
  ClientJoinRoute: ClientJoinRoute,
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientSearchRoute: ClientSearchRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientCategorySlugRoute: ClientCategorySlugRoute,
  ClientEventsIdRoute: ClientEventsIdRoute,
  ClientEventsNewRoute: ClientEventsNewRoute,
  ClientGroupsNewRoute: ClientGroupsNewRoute,
  ClientMessagesIdRoute: ClientMessagesIdRoute,
  ClientPagesSlugRoute: ClientPagesSlugRoute,
  ClientTagsSlugRoute: ClientTagsSlugRoute,
  ClientThreadsIdRoute: ClientThreadsIdRouteWithChildren,
  ClientThreadsNewRoute: ClientThreadsNewRoute,
  ClientCategoryIndexRoute: ClientCategoryIndexRoute,
  ClientEventsIndexRoute: ClientEventsIndexRoute,
  ClientGroupsIndexRoute: ClientGroupsIndexRoute,
  ClientMessagesIndexRoute: ClientMessagesIndexRoute,
  ClientResourcesIndexRoute: ClientResourcesIndexRoute,
  ClientTagsIndexRoute: ClientTagsIndexRoute,
  ClientThreadsIndexRoute: ClientThreadsIndexRoute,
  ClientGroupsSlugEventsRoute: ClientGroupsSlugEventsRoute,
  ClientGroupsSlugMembersRoute: ClientGroupsSlugMembersRoute,
  ClientGroupsSlugSettingsRoute: ClientGroupsSlugSettingsRoute,
  ClientProfileUsernameBadgesRoute: ClientProfileUsernameBadgesRoute,
  ClientProfileUsernameEditRoute: ClientProfileUsernameEditRoute,
  ClientProfileUsernameReputationRoute: ClientProfileUsernameReputationRoute,
  ClientGroupsSlugIndexRoute: ClientGroupsSlugIndexRoute,
  ClientProfileUsernameIndexRoute: ClientProfileUsernameIndexRoute,
  ClientGroupsSlugForumThreadIdRoute: ClientGroupsSlugForumThreadIdRoute,
  ClientGroupsSlugForumIndexRoute: ClientGroupsSlugForumIndexRoute,
  ClientThreadsThreadIdReplyReplyIdEditRoute:
    ClientThreadsThreadIdReplyReplyIdEditRoute,
}

const ClientRouteRouteWithChildren = ClientRouteRoute._addFileChildren(
  ClientRouteRouteChildren,
)

interface LandingRouteRouteChildren {
  LandingCookiesRoute: typeof LandingCookiesRoute
  LandingPrivacyPolicyRoute: typeof LandingPrivacyPolicyRoute
  LandingTermsRoute: typeof LandingTermsRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingCookiesRoute: LandingCookiesRoute,
  LandingPrivacyPolicyRoute: LandingPrivacyPolicyRoute,
  LandingTermsRoute: LandingTermsRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

interface ModeratorRouteRouteChildren {
  ModeratorHelpDocsRoute: typeof ModeratorHelpDocsRoute
  ModeratorModerationRoute: typeof ModeratorModerationRoute
  ModeratorModeratorDashboardRoute: typeof ModeratorModeratorDashboardRoute
  ModeratorModeratorReportsRoute: typeof ModeratorModeratorReportsRoute
}

const ModeratorRouteRouteChildren: ModeratorRouteRouteChildren = {
  ModeratorHelpDocsRoute: ModeratorHelpDocsRoute,
  ModeratorModerationRoute: ModeratorModerationRoute,
  ModeratorModeratorDashboardRoute: ModeratorModeratorDashboardRoute,
  ModeratorModeratorReportsRoute: ModeratorModeratorReportsRoute,
}

const ModeratorRouteRouteWithChildren = ModeratorRouteRoute._addFileChildren(
  ModeratorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ClientRouteRoute: ClientRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
  ModeratorRouteRoute: ModeratorRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
