/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as ClientRouteRouteImport } from './routes/_client/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as LandingTermsRouteImport } from './routes/_landing/terms'
import { Route as LandingPrivacyPolicyRouteImport } from './routes/_landing/privacy-policy'
import { Route as LandingPricingRouteImport } from './routes/_landing/pricing'
import { Route as LandingFeaturesRouteImport } from './routes/_landing/features'
import { Route as LandingCookiesRouteImport } from './routes/_landing/cookies'
import { Route as ClientSettingsRouteImport } from './routes/_client/settings'
import { Route as ClientSearchRouteImport } from './routes/_client/search'
import { Route as ClientReputationRouteImport } from './routes/_client/reputation'
import { Route as ClientNotificationsRouteImport } from './routes/_client/notifications'
import { Route as ClientJoinRouteImport } from './routes/_client/join'
import { Route as ClientEmbedRouteImport } from './routes/_client/embed'
import { Route as ClientBookmarksRouteImport } from './routes/_client/bookmarks'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AdminReportsRouteImport } from './routes/_admin/reports'
import { Route as AdminModerationRouteImport } from './routes/_admin/moderation'
import { Route as AdminHelpRouteImport } from './routes/_admin/help'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminAnnouncementsRouteImport } from './routes/_admin/announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin/analytics'
import { Route as LandingSolutionIndexRouteImport } from './routes/_landing/solution/index'
import { Route as ClientThreadsIndexRouteImport } from './routes/_client/threads/index'
import { Route as ClientTagsIndexRouteImport } from './routes/_client/tags/index'
import { Route as ClientResourcesIndexRouteImport } from './routes/_client/resources/index'
import { Route as ClientMessagesIndexRouteImport } from './routes/_client/messages/index'
import { Route as ClientGroupsIndexRouteImport } from './routes/_client/groups/index'
import { Route as ClientEventsIndexRouteImport } from './routes/_client/events/index'
import { Route as ClientCategoryIndexRouteImport } from './routes/_client/category/index'
import { Route as AdminAppearanceIndexRouteImport } from './routes/_admin/appearance/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LandingSolutionStartupsRouteImport } from './routes/_landing/solution/startups'
import { Route as LandingSolutionOrganizationsRouteImport } from './routes/_landing/solution/organizations'
import { Route as LandingSolutionManagementRouteImport } from './routes/_landing/solution/management'
import { Route as LandingSolutionFreelancersRouteImport } from './routes/_landing/solution/freelancers'
import { Route as LandingSolutionEducationRouteImport } from './routes/_landing/solution/education'
import { Route as LandingSolutionDesignRouteImport } from './routes/_landing/solution/design'
import { Route as LandingSolutionCollaborationRouteImport } from './routes/_landing/solution/collaboration'
import { Route as ClientMessagesIdRouteImport } from './routes/_client/messages/$id'
import { Route as ClientGroupsNewRouteImport } from './routes/_client/groups/new'
import { Route as ClientEventsNewRouteImport } from './routes/_client/events/new'
import { Route as ClientEventsIdRouteImport } from './routes/_client/events/$id'
import { Route as ClientGroupsSlugIndexRouteImport } from './routes/_client/groups/$slug/index'
import { Route as ApiApiAuthSplatRouteImport } from './routes/api/api.auth.$'
import { Route as ClientThreadsThreadIdRouteImport } from './routes/_client/threads/thread.$id'
import { Route as ClientThreadsIdEditRouteImport } from './routes/_client/threads/$id.edit'
import { Route as ClientTagsTagsSlugRouteImport } from './routes/_client/tags/tags.$slug'
import { Route as ClientProfileProfileUsernameRouteImport } from './routes/_client/profile/profile.$username'
import { Route as ClientProfileUsernameEditRouteImport } from './routes/_client/profile/$username/edit'
import { Route as ClientProfileUsernameBadgesRouteImport } from './routes/_client/profile/$username/badges'
import { Route as ClientGroupsSlugSettingsRouteImport } from './routes/_client/groups/$slug/settings'
import { Route as ClientGroupsSlugMembersRouteImport } from './routes/_client/groups/$slug/members'
import { Route as ClientGroupsSlugEventsRouteImport } from './routes/_client/groups/$slug/events'
import { Route as ClientCategoryCategorySlugRouteImport } from './routes/_client/category/category.$slug'
import { Route as ClientThreadsThreadIdReplyReplyIdEditRouteImport } from './routes/_client/threads/$threadId.reply.$replyId.edit'

const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRouteRoute = ClientRouteRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingTermsRoute = LandingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingPrivacyPolicyRoute = LandingPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingPricingRoute = LandingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingFeaturesRoute = LandingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingCookiesRoute = LandingCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LandingRouteRoute,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientSearchRoute = ClientSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientReputationRoute = ClientReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientJoinRoute = ClientJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientEmbedRoute = ClientEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientBookmarksRoute = ClientBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => ClientRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LandingSolutionIndexRoute = LandingSolutionIndexRouteImport.update({
  id: '/solution/',
  path: '/solution/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const ClientThreadsIndexRoute = ClientThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientTagsIndexRoute = ClientTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientResourcesIndexRoute = ClientResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientMessagesIndexRoute = ClientMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientGroupsIndexRoute = ClientGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientEventsIndexRoute = ClientEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientCategoryIndexRoute = ClientCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const AdminAppearanceIndexRoute = AdminAppearanceIndexRouteImport.update({
  id: '/appearance/',
  path: '/appearance/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingSolutionStartupsRoute = LandingSolutionStartupsRouteImport.update({
  id: '/solution/startups',
  path: '/solution/startups',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingSolutionOrganizationsRoute =
  LandingSolutionOrganizationsRouteImport.update({
    id: '/solution/organizations',
    path: '/solution/organizations',
    getParentRoute: () => LandingRouteRoute,
  } as any)
const LandingSolutionManagementRoute =
  LandingSolutionManagementRouteImport.update({
    id: '/solution/management',
    path: '/solution/management',
    getParentRoute: () => LandingRouteRoute,
  } as any)
const LandingSolutionFreelancersRoute =
  LandingSolutionFreelancersRouteImport.update({
    id: '/solution/freelancers',
    path: '/solution/freelancers',
    getParentRoute: () => LandingRouteRoute,
  } as any)
const LandingSolutionEducationRoute =
  LandingSolutionEducationRouteImport.update({
    id: '/solution/education',
    path: '/solution/education',
    getParentRoute: () => LandingRouteRoute,
  } as any)
const LandingSolutionDesignRoute = LandingSolutionDesignRouteImport.update({
  id: '/solution/design',
  path: '/solution/design',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingSolutionCollaborationRoute =
  LandingSolutionCollaborationRouteImport.update({
    id: '/solution/collaboration',
    path: '/solution/collaboration',
    getParentRoute: () => LandingRouteRoute,
  } as any)
const ClientMessagesIdRoute = ClientMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientGroupsNewRoute = ClientGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientEventsNewRoute = ClientEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientEventsIdRoute = ClientEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientGroupsSlugIndexRoute = ClientGroupsSlugIndexRouteImport.update({
  id: '/groups/$slug/',
  path: '/groups/$slug/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ApiApiAuthSplatRoute = ApiApiAuthSplatRouteImport.update({
  id: '/api/api/auth/$',
  path: '/api/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientThreadsThreadIdRoute = ClientThreadsThreadIdRouteImport.update({
  id: '/threads/thread/$id',
  path: '/threads/thread/$id',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientThreadsIdEditRoute = ClientThreadsIdEditRouteImport.update({
  id: '/threads/$id/edit',
  path: '/threads/$id/edit',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientTagsTagsSlugRoute = ClientTagsTagsSlugRouteImport.update({
  id: '/tags/tags/$slug',
  path: '/tags/tags/$slug',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientProfileProfileUsernameRoute =
  ClientProfileProfileUsernameRouteImport.update({
    id: '/profile/profile/$username',
    path: '/profile/profile/$username',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientProfileUsernameEditRoute =
  ClientProfileUsernameEditRouteImport.update({
    id: '/profile/$username/edit',
    path: '/profile/$username/edit',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientProfileUsernameBadgesRoute =
  ClientProfileUsernameBadgesRouteImport.update({
    id: '/profile/$username/badges',
    path: '/profile/$username/badges',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientGroupsSlugSettingsRoute =
  ClientGroupsSlugSettingsRouteImport.update({
    id: '/groups/$slug/settings',
    path: '/groups/$slug/settings',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientGroupsSlugMembersRoute = ClientGroupsSlugMembersRouteImport.update({
  id: '/groups/$slug/members',
  path: '/groups/$slug/members',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientGroupsSlugEventsRoute = ClientGroupsSlugEventsRouteImport.update({
  id: '/groups/$slug/events',
  path: '/groups/$slug/events',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientCategoryCategorySlugRoute =
  ClientCategoryCategorySlugRouteImport.update({
    id: '/category/category/$slug',
    path: '/category/category/$slug',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientThreadsThreadIdReplyReplyIdEditRoute =
  ClientThreadsThreadIdReplyReplyIdEditRouteImport.update({
    id: '/threads/$threadId/reply/$replyId/edit',
    path: '/threads/$threadId/reply/$replyId/edit',
    getParentRoute: () => ClientRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/announcements': typeof AdminAnnouncementsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/help': typeof AdminHelpRoute
  '/moderation': typeof AdminModerationRoute
  '/reports': typeof AdminReportsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/bookmarks': typeof ClientBookmarksRoute
  '/embed': typeof ClientEmbedRoute
  '/join': typeof ClientJoinRoute
  '/notifications': typeof ClientNotificationsRoute
  '/reputation': typeof ClientReputationRoute
  '/search': typeof ClientSearchRoute
  '/settings': typeof ClientSettingsRoute
  '/cookies': typeof LandingCookiesRoute
  '/features': typeof LandingFeaturesRoute
  '/pricing': typeof LandingPricingRoute
  '/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/terms': typeof LandingTermsRoute
  '/events/$id': typeof ClientEventsIdRoute
  '/events/new': typeof ClientEventsNewRoute
  '/groups/new': typeof ClientGroupsNewRoute
  '/messages/$id': typeof ClientMessagesIdRoute
  '/solution/collaboration': typeof LandingSolutionCollaborationRoute
  '/solution/design': typeof LandingSolutionDesignRoute
  '/solution/education': typeof LandingSolutionEducationRoute
  '/solution/freelancers': typeof LandingSolutionFreelancersRoute
  '/solution/management': typeof LandingSolutionManagementRoute
  '/solution/organizations': typeof LandingSolutionOrganizationsRoute
  '/solution/startups': typeof LandingSolutionStartupsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/appearance/': typeof AdminAppearanceIndexRoute
  '/category/': typeof ClientCategoryIndexRoute
  '/events/': typeof ClientEventsIndexRoute
  '/groups/': typeof ClientGroupsIndexRoute
  '/messages/': typeof ClientMessagesIndexRoute
  '/resources/': typeof ClientResourcesIndexRoute
  '/tags/': typeof ClientTagsIndexRoute
  '/threads/': typeof ClientThreadsIndexRoute
  '/solution/': typeof LandingSolutionIndexRoute
  '/category/category/$slug': typeof ClientCategoryCategorySlugRoute
  '/groups/$slug/events': typeof ClientGroupsSlugEventsRoute
  '/groups/$slug/members': typeof ClientGroupsSlugMembersRoute
  '/groups/$slug/settings': typeof ClientGroupsSlugSettingsRoute
  '/profile/$username/badges': typeof ClientProfileUsernameBadgesRoute
  '/profile/$username/edit': typeof ClientProfileUsernameEditRoute
  '/profile/profile/$username': typeof ClientProfileProfileUsernameRoute
  '/tags/tags/$slug': typeof ClientTagsTagsSlugRoute
  '/threads/$id/edit': typeof ClientThreadsIdEditRoute
  '/threads/thread/$id': typeof ClientThreadsThreadIdRoute
  '/api/api/auth/$': typeof ApiApiAuthSplatRoute
  '/groups/$slug/': typeof ClientGroupsSlugIndexRoute
  '/threads/$threadId/reply/$replyId/edit': typeof ClientThreadsThreadIdReplyReplyIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/announcements': typeof AdminAnnouncementsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/help': typeof AdminHelpRoute
  '/moderation': typeof AdminModerationRoute
  '/reports': typeof AdminReportsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/bookmarks': typeof ClientBookmarksRoute
  '/embed': typeof ClientEmbedRoute
  '/join': typeof ClientJoinRoute
  '/notifications': typeof ClientNotificationsRoute
  '/reputation': typeof ClientReputationRoute
  '/search': typeof ClientSearchRoute
  '/settings': typeof ClientSettingsRoute
  '/cookies': typeof LandingCookiesRoute
  '/features': typeof LandingFeaturesRoute
  '/pricing': typeof LandingPricingRoute
  '/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/terms': typeof LandingTermsRoute
  '/events/$id': typeof ClientEventsIdRoute
  '/events/new': typeof ClientEventsNewRoute
  '/groups/new': typeof ClientGroupsNewRoute
  '/messages/$id': typeof ClientMessagesIdRoute
  '/solution/collaboration': typeof LandingSolutionCollaborationRoute
  '/solution/design': typeof LandingSolutionDesignRoute
  '/solution/education': typeof LandingSolutionEducationRoute
  '/solution/freelancers': typeof LandingSolutionFreelancersRoute
  '/solution/management': typeof LandingSolutionManagementRoute
  '/solution/organizations': typeof LandingSolutionOrganizationsRoute
  '/solution/startups': typeof LandingSolutionStartupsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/appearance': typeof AdminAppearanceIndexRoute
  '/category': typeof ClientCategoryIndexRoute
  '/events': typeof ClientEventsIndexRoute
  '/groups': typeof ClientGroupsIndexRoute
  '/messages': typeof ClientMessagesIndexRoute
  '/resources': typeof ClientResourcesIndexRoute
  '/tags': typeof ClientTagsIndexRoute
  '/threads': typeof ClientThreadsIndexRoute
  '/solution': typeof LandingSolutionIndexRoute
  '/category/category/$slug': typeof ClientCategoryCategorySlugRoute
  '/groups/$slug/events': typeof ClientGroupsSlugEventsRoute
  '/groups/$slug/members': typeof ClientGroupsSlugMembersRoute
  '/groups/$slug/settings': typeof ClientGroupsSlugSettingsRoute
  '/profile/$username/badges': typeof ClientProfileUsernameBadgesRoute
  '/profile/$username/edit': typeof ClientProfileUsernameEditRoute
  '/profile/profile/$username': typeof ClientProfileProfileUsernameRoute
  '/tags/tags/$slug': typeof ClientTagsTagsSlugRoute
  '/threads/$id/edit': typeof ClientThreadsIdEditRoute
  '/threads/thread/$id': typeof ClientThreadsThreadIdRoute
  '/api/api/auth/$': typeof ApiApiAuthSplatRoute
  '/groups/$slug': typeof ClientGroupsSlugIndexRoute
  '/threads/$threadId/reply/$replyId/edit': typeof ClientThreadsThreadIdReplyReplyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_client': typeof ClientRouteRouteWithChildren
  '/_landing': typeof LandingRouteRouteWithChildren
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/announcements': typeof AdminAnnouncementsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/help': typeof AdminHelpRoute
  '/_admin/moderation': typeof AdminModerationRoute
  '/_admin/reports': typeof AdminReportsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_client/bookmarks': typeof ClientBookmarksRoute
  '/_client/embed': typeof ClientEmbedRoute
  '/_client/join': typeof ClientJoinRoute
  '/_client/notifications': typeof ClientNotificationsRoute
  '/_client/reputation': typeof ClientReputationRoute
  '/_client/search': typeof ClientSearchRoute
  '/_client/settings': typeof ClientSettingsRoute
  '/_landing/cookies': typeof LandingCookiesRoute
  '/_landing/features': typeof LandingFeaturesRoute
  '/_landing/pricing': typeof LandingPricingRoute
  '/_landing/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/_landing/terms': typeof LandingTermsRoute
  '/_landing/': typeof LandingIndexRoute
  '/_client/events/$id': typeof ClientEventsIdRoute
  '/_client/events/new': typeof ClientEventsNewRoute
  '/_client/groups/new': typeof ClientGroupsNewRoute
  '/_client/messages/$id': typeof ClientMessagesIdRoute
  '/_landing/solution/collaboration': typeof LandingSolutionCollaborationRoute
  '/_landing/solution/design': typeof LandingSolutionDesignRoute
  '/_landing/solution/education': typeof LandingSolutionEducationRoute
  '/_landing/solution/freelancers': typeof LandingSolutionFreelancersRoute
  '/_landing/solution/management': typeof LandingSolutionManagementRoute
  '/_landing/solution/organizations': typeof LandingSolutionOrganizationsRoute
  '/_landing/solution/startups': typeof LandingSolutionStartupsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_admin/appearance/': typeof AdminAppearanceIndexRoute
  '/_client/category/': typeof ClientCategoryIndexRoute
  '/_client/events/': typeof ClientEventsIndexRoute
  '/_client/groups/': typeof ClientGroupsIndexRoute
  '/_client/messages/': typeof ClientMessagesIndexRoute
  '/_client/resources/': typeof ClientResourcesIndexRoute
  '/_client/tags/': typeof ClientTagsIndexRoute
  '/_client/threads/': typeof ClientThreadsIndexRoute
  '/_landing/solution/': typeof LandingSolutionIndexRoute
  '/_client/category/category/$slug': typeof ClientCategoryCategorySlugRoute
  '/_client/groups/$slug/events': typeof ClientGroupsSlugEventsRoute
  '/_client/groups/$slug/members': typeof ClientGroupsSlugMembersRoute
  '/_client/groups/$slug/settings': typeof ClientGroupsSlugSettingsRoute
  '/_client/profile/$username/badges': typeof ClientProfileUsernameBadgesRoute
  '/_client/profile/$username/edit': typeof ClientProfileUsernameEditRoute
  '/_client/profile/profile/$username': typeof ClientProfileProfileUsernameRoute
  '/_client/tags/tags/$slug': typeof ClientTagsTagsSlugRoute
  '/_client/threads/$id/edit': typeof ClientThreadsIdEditRoute
  '/_client/threads/thread/$id': typeof ClientThreadsThreadIdRoute
  '/api/api/auth/$': typeof ApiApiAuthSplatRoute
  '/_client/groups/$slug/': typeof ClientGroupsSlugIndexRoute
  '/_client/threads/$threadId/reply/$replyId/edit': typeof ClientThreadsThreadIdReplyReplyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/announcements'
    | '/dashboard'
    | '/help'
    | '/moderation'
    | '/reports'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/bookmarks'
    | '/embed'
    | '/join'
    | '/notifications'
    | '/reputation'
    | '/search'
    | '/settings'
    | '/cookies'
    | '/features'
    | '/pricing'
    | '/privacy-policy'
    | '/terms'
    | '/events/$id'
    | '/events/new'
    | '/groups/new'
    | '/messages/$id'
    | '/solution/collaboration'
    | '/solution/design'
    | '/solution/education'
    | '/solution/freelancers'
    | '/solution/management'
    | '/solution/organizations'
    | '/solution/startups'
    | '/api/auth/$'
    | '/appearance/'
    | '/category/'
    | '/events/'
    | '/groups/'
    | '/messages/'
    | '/resources/'
    | '/tags/'
    | '/threads/'
    | '/solution/'
    | '/category/category/$slug'
    | '/groups/$slug/events'
    | '/groups/$slug/members'
    | '/groups/$slug/settings'
    | '/profile/$username/badges'
    | '/profile/$username/edit'
    | '/profile/profile/$username'
    | '/tags/tags/$slug'
    | '/threads/$id/edit'
    | '/threads/thread/$id'
    | '/api/api/auth/$'
    | '/groups/$slug/'
    | '/threads/$threadId/reply/$replyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/announcements'
    | '/dashboard'
    | '/help'
    | '/moderation'
    | '/reports'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/bookmarks'
    | '/embed'
    | '/join'
    | '/notifications'
    | '/reputation'
    | '/search'
    | '/settings'
    | '/cookies'
    | '/features'
    | '/pricing'
    | '/privacy-policy'
    | '/terms'
    | '/events/$id'
    | '/events/new'
    | '/groups/new'
    | '/messages/$id'
    | '/solution/collaboration'
    | '/solution/design'
    | '/solution/education'
    | '/solution/freelancers'
    | '/solution/management'
    | '/solution/organizations'
    | '/solution/startups'
    | '/api/auth/$'
    | '/appearance'
    | '/category'
    | '/events'
    | '/groups'
    | '/messages'
    | '/resources'
    | '/tags'
    | '/threads'
    | '/solution'
    | '/category/category/$slug'
    | '/groups/$slug/events'
    | '/groups/$slug/members'
    | '/groups/$slug/settings'
    | '/profile/$username/badges'
    | '/profile/$username/edit'
    | '/profile/profile/$username'
    | '/tags/tags/$slug'
    | '/threads/$id/edit'
    | '/threads/thread/$id'
    | '/api/api/auth/$'
    | '/groups/$slug'
    | '/threads/$threadId/reply/$replyId/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_client'
    | '/_landing'
    | '/_admin/analytics'
    | '/_admin/announcements'
    | '/_admin/dashboard'
    | '/_admin/help'
    | '/_admin/moderation'
    | '/_admin/reports'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/_client/bookmarks'
    | '/_client/embed'
    | '/_client/join'
    | '/_client/notifications'
    | '/_client/reputation'
    | '/_client/search'
    | '/_client/settings'
    | '/_landing/cookies'
    | '/_landing/features'
    | '/_landing/pricing'
    | '/_landing/privacy-policy'
    | '/_landing/terms'
    | '/_landing/'
    | '/_client/events/$id'
    | '/_client/events/new'
    | '/_client/groups/new'
    | '/_client/messages/$id'
    | '/_landing/solution/collaboration'
    | '/_landing/solution/design'
    | '/_landing/solution/education'
    | '/_landing/solution/freelancers'
    | '/_landing/solution/management'
    | '/_landing/solution/organizations'
    | '/_landing/solution/startups'
    | '/api/auth/$'
    | '/_admin/appearance/'
    | '/_client/category/'
    | '/_client/events/'
    | '/_client/groups/'
    | '/_client/messages/'
    | '/_client/resources/'
    | '/_client/tags/'
    | '/_client/threads/'
    | '/_landing/solution/'
    | '/_client/category/category/$slug'
    | '/_client/groups/$slug/events'
    | '/_client/groups/$slug/members'
    | '/_client/groups/$slug/settings'
    | '/_client/profile/$username/badges'
    | '/_client/profile/$username/edit'
    | '/_client/profile/profile/$username'
    | '/_client/tags/tags/$slug'
    | '/_client/threads/$id/edit'
    | '/_client/threads/thread/$id'
    | '/api/api/auth/$'
    | '/_client/groups/$slug/'
    | '/_client/threads/$threadId/reply/$replyId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ClientRouteRoute: typeof ClientRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiApiAuthSplatRoute: typeof ApiApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/terms': {
      id: '/_landing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LandingTermsRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/privacy-policy': {
      id: '/_landing/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LandingPrivacyPolicyRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/pricing': {
      id: '/_landing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof LandingPricingRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/features': {
      id: '/_landing/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof LandingFeaturesRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/cookies': {
      id: '/_landing/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof LandingCookiesRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_client/settings': {
      id: '/_client/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/search': {
      id: '/_client/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ClientSearchRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/reputation': {
      id: '/_client/reputation'
      path: '/reputation'
      fullPath: '/reputation'
      preLoaderRoute: typeof ClientReputationRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/notifications': {
      id: '/_client/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/join': {
      id: '/_client/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof ClientJoinRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/embed': {
      id: '/_client/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof ClientEmbedRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/bookmarks': {
      id: '/_client/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof ClientBookmarksRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_admin/reports': {
      id: '/_admin/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/moderation': {
      id: '/_admin/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/help': {
      id: '/_admin/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/announcements': {
      id: '/_admin/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_landing/solution/': {
      id: '/_landing/solution/'
      path: '/solution'
      fullPath: '/solution/'
      preLoaderRoute: typeof LandingSolutionIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_client/threads/': {
      id: '/_client/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof ClientThreadsIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/tags/': {
      id: '/_client/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof ClientTagsIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/resources/': {
      id: '/_client/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ClientResourcesIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/messages/': {
      id: '/_client/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof ClientMessagesIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/groups/': {
      id: '/_client/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof ClientGroupsIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/events/': {
      id: '/_client/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof ClientEventsIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/category/': {
      id: '/_client/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof ClientCategoryIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_admin/appearance/': {
      id: '/_admin/appearance/'
      path: '/appearance'
      fullPath: '/appearance/'
      preLoaderRoute: typeof AdminAppearanceIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/solution/startups': {
      id: '/_landing/solution/startups'
      path: '/solution/startups'
      fullPath: '/solution/startups'
      preLoaderRoute: typeof LandingSolutionStartupsRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/solution/organizations': {
      id: '/_landing/solution/organizations'
      path: '/solution/organizations'
      fullPath: '/solution/organizations'
      preLoaderRoute: typeof LandingSolutionOrganizationsRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/solution/management': {
      id: '/_landing/solution/management'
      path: '/solution/management'
      fullPath: '/solution/management'
      preLoaderRoute: typeof LandingSolutionManagementRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/solution/freelancers': {
      id: '/_landing/solution/freelancers'
      path: '/solution/freelancers'
      fullPath: '/solution/freelancers'
      preLoaderRoute: typeof LandingSolutionFreelancersRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/solution/education': {
      id: '/_landing/solution/education'
      path: '/solution/education'
      fullPath: '/solution/education'
      preLoaderRoute: typeof LandingSolutionEducationRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/solution/design': {
      id: '/_landing/solution/design'
      path: '/solution/design'
      fullPath: '/solution/design'
      preLoaderRoute: typeof LandingSolutionDesignRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/solution/collaboration': {
      id: '/_landing/solution/collaboration'
      path: '/solution/collaboration'
      fullPath: '/solution/collaboration'
      preLoaderRoute: typeof LandingSolutionCollaborationRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_client/messages/$id': {
      id: '/_client/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof ClientMessagesIdRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/groups/new': {
      id: '/_client/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof ClientGroupsNewRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/events/new': {
      id: '/_client/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof ClientEventsNewRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/events/$id': {
      id: '/_client/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof ClientEventsIdRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/groups/$slug/': {
      id: '/_client/groups/$slug/'
      path: '/groups/$slug'
      fullPath: '/groups/$slug/'
      preLoaderRoute: typeof ClientGroupsSlugIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/api/api/auth/$': {
      id: '/api/api/auth/$'
      path: '/api/api/auth/$'
      fullPath: '/api/api/auth/$'
      preLoaderRoute: typeof ApiApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/threads/thread/$id': {
      id: '/_client/threads/thread/$id'
      path: '/threads/thread/$id'
      fullPath: '/threads/thread/$id'
      preLoaderRoute: typeof ClientThreadsThreadIdRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/threads/$id/edit': {
      id: '/_client/threads/$id/edit'
      path: '/threads/$id/edit'
      fullPath: '/threads/$id/edit'
      preLoaderRoute: typeof ClientThreadsIdEditRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/tags/tags/$slug': {
      id: '/_client/tags/tags/$slug'
      path: '/tags/tags/$slug'
      fullPath: '/tags/tags/$slug'
      preLoaderRoute: typeof ClientTagsTagsSlugRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/profile/profile/$username': {
      id: '/_client/profile/profile/$username'
      path: '/profile/profile/$username'
      fullPath: '/profile/profile/$username'
      preLoaderRoute: typeof ClientProfileProfileUsernameRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/profile/$username/edit': {
      id: '/_client/profile/$username/edit'
      path: '/profile/$username/edit'
      fullPath: '/profile/$username/edit'
      preLoaderRoute: typeof ClientProfileUsernameEditRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/profile/$username/badges': {
      id: '/_client/profile/$username/badges'
      path: '/profile/$username/badges'
      fullPath: '/profile/$username/badges'
      preLoaderRoute: typeof ClientProfileUsernameBadgesRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/groups/$slug/settings': {
      id: '/_client/groups/$slug/settings'
      path: '/groups/$slug/settings'
      fullPath: '/groups/$slug/settings'
      preLoaderRoute: typeof ClientGroupsSlugSettingsRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/groups/$slug/members': {
      id: '/_client/groups/$slug/members'
      path: '/groups/$slug/members'
      fullPath: '/groups/$slug/members'
      preLoaderRoute: typeof ClientGroupsSlugMembersRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/groups/$slug/events': {
      id: '/_client/groups/$slug/events'
      path: '/groups/$slug/events'
      fullPath: '/groups/$slug/events'
      preLoaderRoute: typeof ClientGroupsSlugEventsRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/category/category/$slug': {
      id: '/_client/category/category/$slug'
      path: '/category/category/$slug'
      fullPath: '/category/category/$slug'
      preLoaderRoute: typeof ClientCategoryCategorySlugRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/threads/$threadId/reply/$replyId/edit': {
      id: '/_client/threads/$threadId/reply/$replyId/edit'
      path: '/threads/$threadId/reply/$replyId/edit'
      fullPath: '/threads/$threadId/reply/$replyId/edit'
      preLoaderRoute: typeof ClientThreadsThreadIdReplyReplyIdEditRouteImport
      parentRoute: typeof ClientRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminAppearanceIndexRoute: typeof AdminAppearanceIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminAppearanceIndexRoute: AdminAppearanceIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ClientRouteRouteChildren {
  ClientBookmarksRoute: typeof ClientBookmarksRoute
  ClientEmbedRoute: typeof ClientEmbedRoute
  ClientJoinRoute: typeof ClientJoinRoute
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientReputationRoute: typeof ClientReputationRoute
  ClientSearchRoute: typeof ClientSearchRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientEventsIdRoute: typeof ClientEventsIdRoute
  ClientEventsNewRoute: typeof ClientEventsNewRoute
  ClientGroupsNewRoute: typeof ClientGroupsNewRoute
  ClientMessagesIdRoute: typeof ClientMessagesIdRoute
  ClientCategoryIndexRoute: typeof ClientCategoryIndexRoute
  ClientEventsIndexRoute: typeof ClientEventsIndexRoute
  ClientGroupsIndexRoute: typeof ClientGroupsIndexRoute
  ClientMessagesIndexRoute: typeof ClientMessagesIndexRoute
  ClientResourcesIndexRoute: typeof ClientResourcesIndexRoute
  ClientTagsIndexRoute: typeof ClientTagsIndexRoute
  ClientThreadsIndexRoute: typeof ClientThreadsIndexRoute
  ClientCategoryCategorySlugRoute: typeof ClientCategoryCategorySlugRoute
  ClientGroupsSlugEventsRoute: typeof ClientGroupsSlugEventsRoute
  ClientGroupsSlugMembersRoute: typeof ClientGroupsSlugMembersRoute
  ClientGroupsSlugSettingsRoute: typeof ClientGroupsSlugSettingsRoute
  ClientProfileUsernameBadgesRoute: typeof ClientProfileUsernameBadgesRoute
  ClientProfileUsernameEditRoute: typeof ClientProfileUsernameEditRoute
  ClientProfileProfileUsernameRoute: typeof ClientProfileProfileUsernameRoute
  ClientTagsTagsSlugRoute: typeof ClientTagsTagsSlugRoute
  ClientThreadsIdEditRoute: typeof ClientThreadsIdEditRoute
  ClientThreadsThreadIdRoute: typeof ClientThreadsThreadIdRoute
  ClientGroupsSlugIndexRoute: typeof ClientGroupsSlugIndexRoute
  ClientThreadsThreadIdReplyReplyIdEditRoute: typeof ClientThreadsThreadIdReplyReplyIdEditRoute
}

const ClientRouteRouteChildren: ClientRouteRouteChildren = {
  ClientBookmarksRoute: ClientBookmarksRoute,
  ClientEmbedRoute: ClientEmbedRoute,
  ClientJoinRoute: ClientJoinRoute,
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientReputationRoute: ClientReputationRoute,
  ClientSearchRoute: ClientSearchRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientEventsIdRoute: ClientEventsIdRoute,
  ClientEventsNewRoute: ClientEventsNewRoute,
  ClientGroupsNewRoute: ClientGroupsNewRoute,
  ClientMessagesIdRoute: ClientMessagesIdRoute,
  ClientCategoryIndexRoute: ClientCategoryIndexRoute,
  ClientEventsIndexRoute: ClientEventsIndexRoute,
  ClientGroupsIndexRoute: ClientGroupsIndexRoute,
  ClientMessagesIndexRoute: ClientMessagesIndexRoute,
  ClientResourcesIndexRoute: ClientResourcesIndexRoute,
  ClientTagsIndexRoute: ClientTagsIndexRoute,
  ClientThreadsIndexRoute: ClientThreadsIndexRoute,
  ClientCategoryCategorySlugRoute: ClientCategoryCategorySlugRoute,
  ClientGroupsSlugEventsRoute: ClientGroupsSlugEventsRoute,
  ClientGroupsSlugMembersRoute: ClientGroupsSlugMembersRoute,
  ClientGroupsSlugSettingsRoute: ClientGroupsSlugSettingsRoute,
  ClientProfileUsernameBadgesRoute: ClientProfileUsernameBadgesRoute,
  ClientProfileUsernameEditRoute: ClientProfileUsernameEditRoute,
  ClientProfileProfileUsernameRoute: ClientProfileProfileUsernameRoute,
  ClientTagsTagsSlugRoute: ClientTagsTagsSlugRoute,
  ClientThreadsIdEditRoute: ClientThreadsIdEditRoute,
  ClientThreadsThreadIdRoute: ClientThreadsThreadIdRoute,
  ClientGroupsSlugIndexRoute: ClientGroupsSlugIndexRoute,
  ClientThreadsThreadIdReplyReplyIdEditRoute:
    ClientThreadsThreadIdReplyReplyIdEditRoute,
}

const ClientRouteRouteWithChildren = ClientRouteRoute._addFileChildren(
  ClientRouteRouteChildren,
)

interface LandingRouteRouteChildren {
  LandingCookiesRoute: typeof LandingCookiesRoute
  LandingFeaturesRoute: typeof LandingFeaturesRoute
  LandingPricingRoute: typeof LandingPricingRoute
  LandingPrivacyPolicyRoute: typeof LandingPrivacyPolicyRoute
  LandingTermsRoute: typeof LandingTermsRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LandingSolutionCollaborationRoute: typeof LandingSolutionCollaborationRoute
  LandingSolutionDesignRoute: typeof LandingSolutionDesignRoute
  LandingSolutionEducationRoute: typeof LandingSolutionEducationRoute
  LandingSolutionFreelancersRoute: typeof LandingSolutionFreelancersRoute
  LandingSolutionManagementRoute: typeof LandingSolutionManagementRoute
  LandingSolutionOrganizationsRoute: typeof LandingSolutionOrganizationsRoute
  LandingSolutionStartupsRoute: typeof LandingSolutionStartupsRoute
  LandingSolutionIndexRoute: typeof LandingSolutionIndexRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingCookiesRoute: LandingCookiesRoute,
  LandingFeaturesRoute: LandingFeaturesRoute,
  LandingPricingRoute: LandingPricingRoute,
  LandingPrivacyPolicyRoute: LandingPrivacyPolicyRoute,
  LandingTermsRoute: LandingTermsRoute,
  LandingIndexRoute: LandingIndexRoute,
  LandingSolutionCollaborationRoute: LandingSolutionCollaborationRoute,
  LandingSolutionDesignRoute: LandingSolutionDesignRoute,
  LandingSolutionEducationRoute: LandingSolutionEducationRoute,
  LandingSolutionFreelancersRoute: LandingSolutionFreelancersRoute,
  LandingSolutionManagementRoute: LandingSolutionManagementRoute,
  LandingSolutionOrganizationsRoute: LandingSolutionOrganizationsRoute,
  LandingSolutionStartupsRoute: LandingSolutionStartupsRoute,
  LandingSolutionIndexRoute: LandingSolutionIndexRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ClientRouteRoute: ClientRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiApiAuthSplatRoute: ApiApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
